#!/bin/bash
echo 'NCH Arch Installer'
echo 'THIS WILL WIPE AN ENTIRE PHYSICAL DISK'
echo 'Make sure system is connected to the internet and keyboard layout is set'
echo 'and execute INSIDE the archscripts folder'
read -p '[Press any key to continue]'

SCRIPTS_LOCATION=$(pwd)

# --- Preinstall --- #
# 1.6: Verify boot mode
ls /sys/firmware/efi/efivars &&
# 1.7: Verify connection
ping -c 5 archlinux.org &&
# 1.8: Update the system clock
timedatectl &&
read -p '[Press any key to continue]'
# 1.9: Update the system clock
lsblk &&
echo "Where to install? (e.g. /dev/sda)" &&
read -p DISK &&
read -p "THIS WILL WIPE THE DISK $DISK [Press any key to continue]" &&
## Disk wiping
wipefs --all ${DISK} &&
## Disk partitioning
echo "label: gpt
device: ${DISK}
unit: sectors

${DISK}1 : size=2048MiB, type=UEFI
${DISK}2 : size=2GiB, type=SWAP
${DISK}3 : type=23
" | sfdisk ${DISK} &&
# 1.10 Formatting
mkfs.fat -F 32 -n BOOTP ${DISK}1 &&
mkswap -L SWAPP ${DISK}2 &&
mkfs.ext4 -L ROOTP ${DISK}3 &&
# 1.11 Mounting
mount ${DISK}3 /mnt &&
mount --mkdir ${DISK}1 /mnt/boot &&
swapon ${DISK}2
# --- Install --- #
# 2.1 Essential packages
cat packages_01 | pacstrap -K /mnt - &&
# --- Config --- #
# 3.1 Fstab
genfstab -U /mnt >> /mnt/etc/fstab
cat /mnt/etc/fstab

# Copy files to new system
cp * /mnt/root
echo 'Scripts copied to new stystem'
echo 'Please chroot into new system /root and execute next script (arch-chroot /mnt)'
