#!/bin/bash
set -e

echo 'NCH Arch Installer (post-reboot config.)'
read -p '[Press any key to continue]'

# finish network config
echo "Network config..."
systemctl enable NetworkManager.service
systemctl start NetworkManager.service

echo "bootctl config..."
echo "MAKE SURE SECUREBOOT IS OFF"
# Set up systemdboot autoupdates
systemctl enable systemd-boot-update.service

echo "Copying pacman config..."
# Pacman config
cp /etc/pacman.conf /etc/pacman.conf.backup
cat install_resources/pacman.conf > /etc/pacman.conf

echo "User config"
# Create user
read -p "Real name: " NAME_INPUT
read -p "Username: " USERNAME_INPUT
useradd -m -c "$NAME_INPUT" $USERNAME_INPUT
passwd $USERNAME_INPUT
gpasswd -a $USERNAME_INPUT wheel
echo "User added to wheel group"

echo "Copying scripts to user home folder"
# Move scripts to user dir
mkdir /home/${USERNAME_INPUT}/.archscripts
cp -r * /home/${USERNAME_INPUT}/.archscripts

chown -R $USERNAME_INPUT /home/$USERNAME_INPUT

read -p '[Press any key to edit sudoers]'
EDITOR=rvim visudo

echo "Packages download..."
# Install my packages
cat install_resources/packages_02 | pacman -Syu --needed --noconfirm -

echo "Reflector config..."
# Reflector
systemctl enable reflector.service

echo "Energy config..."
# ThermalD & powerprofilesdaemon
echo "Setting up thermald"
systemctl enable thermald.service

echo "Setting up makepkg.conf to enable optimized binaries"
# makepkg
cp /etc/makepkg.conf /etc/makepkg.conf.backup
cat install_resources/makepkg.conf > /etc/makepkg.conf
echo "Remember to set up number of threads in makepkg.conf"

echo "Disabling hibernation"
mkdir /etc/systemd/sleep.conf.d
cp install_resources/00-disable-hibernation.conf /etc/systemd/sleep.conf.d/00-disable-hibernation.conf

echo "Locking root user"
passwd --lock root

echo "Congratulations. You have a minimal Arch Installation!"
