#!/bin/bash
set -e

echo "Budgie installer.
DONT run as root."
read -p "[Any key to continue]"

echo "Installing pipewire packages"
cat desktop/pipewire_packs | sudo pacman -Syu --needed --noconfirm -

echo "Installing Xorg"
sudo pacman -S --needed --noconfirm xorg xorg-server xorg-apps
echo "Changing keyboard layout"
sudo cp install_resources/00-keyboard.conf /etc/X11/xorg.conf.d/

echo "Installing Budgie packages"
cat desktop/budgie/budgie_packs | sudo pacman -S --needed --noconfirm -

echo "Installing user packages"
cat desktop/ui_packages | sudo pacman -S --needed --noconfirm -

echo "Creating user directories"
sudo pacman -S --noconfirm --asdeps xdg-user-dirs
xdg-user-dirs-update

echo "Enabling firewalld"
sudo systemctl enable firewalld.service

echo "Setting up power-profiles-daemon"
sudo systemctl enable power-profiles-daemon.service

echo "Enabling LightDM"
sudo systemctl enable lightdm.service

echo "Installing additional fonts"
cat desktop/fontlist | sudo pacman -S --needed --noconfirm -

read -p "[Any key to reboot and finalize]"

sudo systemctl reboot
