#!/bin/bash
echo "GNOME installer.
DONT run as root."
read -p "[Any key to continue]"

echo "Installing pipewire packages"
# Pipewire
cat desktop/pipewire_packs | sudo pacman -Syu --needed --noconfirm -

echo "Installing GNOME packages"
# GNOME
cat /desktop/gnome/gnome_packs | sudo pacman -S --needed --noconfirm -

echo "Installing user packages"
# UI Packs
# GNOME
cat desktop/ui_packages | sudo pacman -S --needed --noconfirm -

echo "Enabling GDM"
# GDM
sudo systemctl enable gdm.service

echo "Enabling Firefox Wayland"
# Wayland for Firefox
cat desktop/bashprofile_complements >> ~/.bash_profile

echo "Installing additional fonts"
# Fonts
cat desktop/fontlist | sudo pacman -S --needed --noconfirm -

read -p "[Any key to reboot and finalize]"

# End & reboot
sudo systemctl reboot
