#!/bin/bash
echo "GNOME installer.
For security, dont run as root."
read -p "[Any key to continue]"

# Pipewire
cat pipewire_packages | sudo pacman -Syu --needed --noconfirm -

# Fonts
cat fontlist | sudo pacman -S --needed --noconfirm -

# GNOME
cat gnome_packages | sudo pacman -S --needed --noconfirm -

# UI Packs
# GNOME
cat ui_packages | sudo pacman -S --needed --noconfirm -

# GDM
sudo systemctl enable gdm.service

# Wayland for Firefox
cat bashprofile_complements >> ~/.bash_profile

# End & reboot
sudo systemctl reboot
