#!/bin/bash
set -e

echo "KDE installer.
DONT run as root."
read -p "[Any key to continue]"

# Pipewire
echo "Installing pipewire packages"
cat desktop/pipewire_packs | sudo pacman -Syu --needed --noconfirm -

# Xorg
echo "Installing Xorg"
sudo pacman -S --needed --noconfirm xorg xorg-server xorg-apps
## Keyboard conf
echo "Changing keyboard layout"
sudo cp install_resources/00-keyboard.conf /etc/X11/xorg.conf.d/

echo "Installing KDE packages"
# KDE
cat desktop/kde/kde_packs | sudo pacman -S --needed --noconfirm -

echo "Installing user packages"
# UI Packs
cat desktop/ui_packages | sudo pacman -S --needed --noconfirm -

# Session manager
echo "Enabling SDDM"
sudo systemctl enable sddm.service

# Enable CUPS
echo "Enabling CUPS"
sudo systemctl enable cups.socket

# Fonts
echo "Installing additional fonts"
cat desktop/fontlist | sudo pacman -S --needed --noconfirm -

echo "Enabling Firefox Wayland"
# Wayland for Firefox
cat desktop/bashprofile_complements >> ~/.bash_profile

read -p "[Any key to reboot and finalize]"

# End & reboot
sudo systemctl reboot
