#!/bin/bash
set -e

echo "Xfce installer.
DONT run as root."
read -p "[Any key to continue]"

# Pipewire
echo "Installing pipewire packages"
cat desktop/pipewire_packs | sudo pacman -Syu --needed --noconfirm -

# Xorg
echo "Installing Xorg"
sudo pacman -S --needed --noconfirm xorg xorg-server xorg-apps
## Keyboard conf
echo "Changing keyboard layout"
sudo cp install_resources/00-keyboard.conf /etc/X11/xorg.conf.d/

echo "Installing Xfce packages"
# XFCE
cat desktop/xfce/xfce_packs | sudo pacman -S --needed --noconfirm -

echo "Installing user packages"
# UI Packs
cat desktop/ui_packages | sudo pacman -S --needed --noconfirm -

# Session manager
echo "Enabling LightDM"
sudo systemctl enable lightdm.service

# Enable CUPS
echo "Enabling CUPS"
sudo systemctl enable cups.socket

# Fonts
echo "Installing additional fonts"
cat desktop/fontlist | sudo pacman -S --needed --noconfirm -

echo "Creating user directories"
xdg-user-dirs-update

read -p "[Any key to reboot and finalize]"

# End & reboot
sudo systemctl reboot
